import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { CookiesProvider } from "next-client-cookies/server";
import AuthProvider from "../Provider";
import Nav from "./components/Nav";

const inter = Inter({ subsets: ["latin"] });
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthProvider>
          <CookiesProvider>
            <Nav />
            <div className="flex justify-center p-9 relative top-12">
              {children}
            </div>
          </CookiesProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
